### ISSUE TITLE
Add detailed info regarding collection timerange

### ISSUE THREAD

**Issue by oa123123** [rfizzle/gsuite-collector#4]
something like this
![image](https://user-images.githubusercontent.com/41897034/125583547-e1c3e2d9-d11a-43a0-956f-25f55fcac620.png)

To allow the user to see which times are being pulled.

**Comment by rfizzle** [comment]
@oa123123 Check out https://github.com/rfizzle/log-collector

I merged all my collectors into a single app to support more inputs/outputs. I added a dynamic offset based on the poll time specified, and it should have detailed logging via the verbose flag. Let me know if this doesn't cover your use cases and I'll see about adding more.
